name       : sonivox
version    : 3.6.12
release    : 2
source     :
    - https://github.com/pedrolcl/sonivox/archive/refs/tags/v3.6.12.tar.gz : 23a7f29c617e791dfcb50b75eef41464e4bf3fca15b19da395a64373ff5d8456
license    : Apache-2.0
summary    : Library for wavetable and realtime GM synthesis
component  : programming.library
description: |
        A library for wavetable and realtime GM synthesis. A fork of the AOSP 'platform_external_sonivox' project.
setup      : |
    %cmake_ninja -DBUILD_SONIVOX_STATIC=OFF -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
