name       : sonivox
version    : 3.6.11
release    : 1
source     :
    - https://github.com/pedrolcl/sonivox/archive/refs/tags/v3.6.11.tar.gz : 7d7f34508c5475dc6f1c13d1facea084c17a5bca73d085ee9842dae62329a473
license    : Apache-2.0
summary    : Library for wavetable and realtime GM synthesis
component  : programming.library
description: |
        A library for wavetable and realtime GM synthesis. A fork of the AOSP 'platform_external_sonivox' project.
setup      : |
    %cmake_ninja -DBUILD_SONIVOX_STATIC=OFF -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
